[package]
name = "clipboard-core"
version = "0.1.4"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rusqlite = { version = "0.38", features = ["bundled", "backup"] }
sha2 = "0.10"
thiserror.workspace = true
serde_json.workspace = true
url = "2.5"
percent-encoding = "2"
tempfile = "3"
regex-lite = "=0.1.9"
