use clipboard_core::*;

fn policy() -> CapturePolicy {
    CapturePolicy {
        enabled: true,
        ..Default::default()
    }
}
fn text(value: &str, time: u64) -> Input {
    Input {
        representations: vec![Representation {
            format: "text/plain".into(),
            bytes: value.as_bytes().to_vec(),
        }],
        source_application: "test.app".into(),
        observed_types: vec![],
        copied_at_ms: time,
    }
}
fn list(history: &mut History) -> Vec<Entry> {
    history.list("", false, 0, 100, 100).unwrap()
}

#[test]
fn persistence_unicode_search_and_rich_text_roundtrip() {
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("history.sqlite3");
    let id;
    {
        let mut history = History::open(&path, Limits::default(), 100).unwrap();
        let mut input = text("你好 ÄBC\n keep spaces ", 100);
        input.representations.push(Representation {
            format: "text/html".into(),
            bytes: b"<b>hello</b>".to_vec(),
        });
        id = history.record(input.clone(), &policy()).unwrap().unwrap();
        assert_eq!(history.payload(id).unwrap().len(), 2);
        assert_eq!(history.list("äbc", false, 0, 100, 100).unwrap()[0].id, id);
        history.set_pinned(id, true, 100).unwrap();
    }
    let mut history = History::open(path, Limits::default(), 100).unwrap();
    let entries = list(&mut history);
    assert!(entries[0].pinned);
    assert_eq!(entries[0].id, id);
    let payload = history.payload(id).unwrap();
    assert_eq!(
        payload
            .iter()
            .find(|r| r.format == "text/plain")
            .unwrap()
            .bytes,
        "你好 ÄBC\n keep spaces ".as_bytes()
    );
}

#[test]
fn duplicate_promotes_recency_preserves_pin_and_replaces_formats() {
    let mut history = History::open(":memory:", Limits::default(), 100).unwrap();
    let id = history.record(text("same", 1), &policy()).unwrap().unwrap();
    history.set_pinned(id, true, 100).unwrap();
    history.record(text("other", 2), &policy()).unwrap();
    let mut input = text("same", 3);
    input.representations.push(Representation {
        format: "text/rtf".into(),
        bytes: b"{\\rtf1 same}".to_vec(),
    });
    assert_eq!(history.record(input, &policy()).unwrap(), Some(id));
    assert_eq!(history.stats().unwrap().items, 2);
    assert!(list(&mut history)[0].pinned);
    assert_eq!(list(&mut history)[0].copied_at_ms, 3);
    assert_eq!(history.payload(id).unwrap().len(), 2);
}

#[test]
fn all_sensitive_markers_and_disabled_or_ignored_apps_never_persist() {
    let mut history = History::open(":memory:", Limits::default(), 100).unwrap();
    assert!(
        history
            .record(text("secret", 1), &CapturePolicy::default())
            .unwrap()
            .is_none()
    );
    let mut ignored = policy();
    ignored.ignored_applications.push("test.app".into());
    assert!(
        history
            .record(text("secret", 1), &ignored)
            .unwrap()
            .is_none()
    );
    for marker in [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
    ] {
        let mut input = text("secret", 1);
        input.observed_types.push(marker.into());
        assert!(history.record(input, &policy()).unwrap().is_none());
    }
    ignored.ignored_applications.clear();
    ignored.ignored_types.push("private.custom".into());
    assert!(!should_capture(
        &ignored,
        "test.app",
        &["private.custom".into()]
    ));
    assert_eq!(history.stats().unwrap().items, 0);
}

#[test]
fn limits_evict_oldest_nonpinned_and_capacity_failure_rolls_back() {
    let limits = Limits {
        maximum_items: 2,
        ..Limits::default()
    };
    let mut history = History::open(":memory:", limits, 100).unwrap();
    let a = history.record(text("a", 1), &policy()).unwrap().unwrap();
    history.set_pinned(a, true, 100).unwrap();
    let b = history.record(text("b", 2), &policy()).unwrap().unwrap();
    let c = history.record(text("c", 3), &policy()).unwrap().unwrap();
    assert!(matches!(history.payload(b), Err(Error::NotFound)));
    history.set_pinned(c, true, 100).unwrap();
    let before = history.stats().unwrap();
    assert!(matches!(
        history.record(text("d", 4), &policy()),
        Err(Error::Capacity)
    ));
    assert_eq!(history.stats().unwrap(), before);
    assert!(matches!(
        history.configure(
            Limits {
                maximum_items: 1,
                ..limits
            },
            100
        ),
        Err(Error::Capacity)
    ));
    assert_eq!(history.stats().unwrap(), before);
    history.clear(false).unwrap();
    assert_eq!(history.stats().unwrap().items, 2);
    history.clear(true).unwrap();
    assert_eq!(history.stats().unwrap().items, 0);
}

#[test]
fn expiry_keeps_pins_and_bounds_are_enforced() {
    let limits = Limits {
        maximum_item_bytes: 10,
        retention_days: 1,
        ..Limits::default()
    };
    let mut history = History::open(":memory:", limits, 100).unwrap();
    let id = history.record(text("pin", 1), &policy()).unwrap().unwrap();
    history.set_pinned(id, true, 100).unwrap();
    history.record(text("expire", 2), &policy()).unwrap();
    assert!(matches!(
        history.record(text("too much text", 3), &policy()),
        Err(Error::TooLarge)
    ));
    assert!(
        history
            .record(text(" \n ", 3), &policy())
            .unwrap()
            .is_none()
    );
    let entries = history.list("", false, 0, 100, 2 * 86_400_000).unwrap();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].id, id);
    assert!(matches!(
        History::open(
            ":memory:",
            Limits {
                maximum_items: 0,
                ..limits
            },
            0
        ),
        Err(Error::InvalidInput)
    ));
}

#[test]
fn byte_budget_and_image_payloads_are_bounded_and_lazy() {
    let limits = Limits {
        maximum_bytes: 60,
        maximum_item_bytes: 40,
        ..Limits::default()
    };
    let mut history = History::open(":memory:", limits, 100).unwrap();
    history.record(text("first ten!", 1), &policy()).unwrap();
    let second = history
        .record(text("second one", 2), &policy())
        .unwrap()
        .unwrap();
    assert!(history.stats().unwrap().bytes <= 60);
    assert_eq!(history.stats().unwrap().items, 1);
    assert_eq!(list(&mut history)[0].id, second);
    let input = Input {
        representations: vec![Representation {
            format: "image/png".into(),
            bytes: b"\x89PNG\r\n\x1a\nfixture".to_vec(),
        }],
        source_application: "test.app".into(),
        observed_types: vec![],
        copied_at_ms: 3,
    };
    let id = history.record(input, &policy()).unwrap().unwrap();
    let entries = list(&mut history);
    assert_eq!(entries[0].kind, Kind::Image);
    assert!(entries[0].preview.is_empty());
    assert_eq!(history.payload(id).unwrap()[0].format, "image/png");
}

#[test]
fn rejects_future_schema_without_overwriting_and_invalid_payloads() {
    let directory = tempfile::tempdir().unwrap();
    let path = directory.path().join("future.sqlite3");
    rusqlite::Connection::open(&path)
        .unwrap()
        .execute_batch("PRAGMA user_version=99")
        .unwrap();
    assert!(matches!(
        History::open(path, Limits::default(), 100),
        Err(Error::UnsupportedSchema)
    ));
    let mut history = History::open(":memory:", Limits::default(), 100).unwrap();
    let mut input = text("valid", 1);
    input.representations.push(input.representations[0].clone());
    assert!(matches!(
        history.record(input, &policy()),
        Err(Error::InvalidInput)
    ));
    let mut input = text("valid", 1);
    input.representations[0].bytes = vec![255];
    assert!(matches!(
        history.record(input, &policy()),
        Err(Error::InvalidInput)
    ));
    assert!(matches!(history.delete(123), Err(Error::NotFound)));
    assert!(matches!(history.payload(123), Err(Error::NotFound)));
}

#[test]
fn image_dimension_budget_rejects_overflow_and_zero_dimensions() {
    assert!(image_dimensions_allowed(4000, 4000));
    assert!(!image_dimensions_allowed(4001, 4000));
    assert!(!image_dimensions_allowed(0, 100));
    assert!(!image_dimensions_allowed(u64::MAX, 2));
}

#[test]
fn failed_duplicate_growth_preserves_existing_payload_and_pin() {
    let limits = Limits {
        maximum_bytes: 40,
        maximum_item_bytes: 40,
        ..Limits::default()
    };
    let mut history = History::open(":memory:", limits, 100).unwrap();
    let id = history.record(text("a", 1), &policy()).unwrap().unwrap();
    history.set_pinned(id, true, 100).unwrap();
    let other = history.record(text("b", 2), &policy()).unwrap().unwrap();
    history.set_pinned(other, true, 100).unwrap();
    let before = history.payload(id).unwrap();
    let mut input = text("a", 3);
    input.representations.push(Representation {
        format: "text/html".into(),
        bytes: vec![b'x'; 30],
    });
    assert!(matches!(
        history.record(input, &policy()),
        Err(Error::Capacity) | Err(Error::TooLarge)
    ));
    assert_eq!(history.payload(id).unwrap(), before);
    assert_eq!(list(&mut history)[0].copied_at_ms, 2);
}
