[package]
name = "polyglance-cabi"
version = "0.1.4"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
capture-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
translator-core.workspace = true
translator-providers.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "ApplicationModel",
    "Foundation",
    "Foundation_Collections",
    "Globalization",
    "Graphics_Capture",
    "Graphics_DirectX",
    "Graphics_DirectX_Direct3D11",
    "Graphics_Imaging",
    "Media_Core",
    "Media_Editing",
    "Media_MediaProperties",
    "Media_Ocr",
    "Media_Transcoding",
    "Services_Store",
    "Storage",
    "Storage_Streams",
    "Win32",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_System_Com",
    "Win32_System_WinRT_Direct3D11",
    "Win32_System_WinRT_Graphics_Capture",
    "Win32_Media_MediaFoundation",
] }
