[package]
name = "polyglance-cabi"
version = "0.0.3"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
capture-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
translator-core.workspace = true
translator-providers.workspace = true
