name = "polyglance"
compatibility_date = "2026-08-31"
pages_build_output_dir = "dist"

[observability]
enabled = true

[[kv_namespaces]]
binding = "POLYGLANCE_STATS"
id = "eda4b111044147eab0964c335b3b9d45"
