//! Portable clipboard history, metadata, search and retention. Native APIs stay in frontends.
mod backup;
pub use backup::{BackupInfo, RestoreMode, RestoreReport, inspect_backup, recover_database};
use rusqlite::{Connection, Transaction, params};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

const SCHEMA_VERSION: i64 = 2;
const DAY_MS: u64 = 86_400_000;
const MAX_OCR_BYTES: usize = 1_000_000;
const MAX_BUNDLE_ITEMS: usize = 100;
const FILE_FORMAT: &str = "text/uri-list";
const ALLOWED_FORMATS: &[&str] = &[
    "text/plain",
    "text/html",
    "text/rtf",
    "image/png",
    FILE_FORMAT,
];
const PRIVATE_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
    "polyglance.clipboard.confidential",
];

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("invalid history configuration or content")]
    InvalidInput,
    #[error("unsupported database schema")]
    UnsupportedSchema,
    #[error("clipboard content exceeds the per-item limit")]
    TooLarge,
    #[error("pinned records fill the history capacity")]
    Capacity,
    #[error("history record does not exist")]
    NotFound,
    #[error("history database or backup is damaged")]
    Corrupt,
    #[error("history storage failed")]
    Storage(#[from] rusqlite::Error),
    #[error("history file operation failed")]
    Io(#[from] std::io::Error),
}
#[derive(Clone, Copy, Debug)]
pub struct Limits {
    pub maximum_items: u32,
    pub maximum_bytes: u64,
    pub maximum_item_bytes: u64,
    /// Zero means no expiration. Pinned records never expire automatically.
    pub retention_days: u32,
}
impl Default for Limits {
    fn default() -> Self {
        Self {
            maximum_items: 500,
            maximum_bytes: 256 * 1024 * 1024,
            maximum_item_bytes: 16 * 1024 * 1024,
            retention_days: 30,
        }
    }
}
impl Limits {
    pub fn validate(self) -> Result<Self, Error> {
        if self.maximum_items == 0
            || self.maximum_items > 10_000
            || self.maximum_item_bytes == 0
            || self.maximum_item_bytes > self.maximum_bytes
            || self.maximum_bytes > 2 * 1024 * 1024 * 1024
            || self.retention_days > 3650
        {
            return Err(Error::InvalidInput);
        }
        Ok(self)
    }
}
#[derive(Clone, Debug, Default)]
pub struct CapturePolicy {
    pub enabled: bool,
    pub ignored_applications: Vec<String>,
    pub ignored_types: Vec<String>,
}
pub fn should_capture(policy: &CapturePolicy, source: &str, types: &[String]) -> bool {
    policy.enabled
        && !policy.ignored_applications.iter().any(|app| app == source)
        && !types
            .iter()
            .any(|ty| PRIVATE_TYPES.contains(&ty.as_str()) || policy.ignored_types.contains(ty))
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Representation {
    pub format: String,
    pub bytes: Vec<u8>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ClipboardItem {
    pub representations: Vec<Representation>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Text,
    Image,
    File,
    Multiple,
}
impl Kind {
    fn number(self) -> i64 {
        match self {
            Self::Text => 0,
            Self::Image => 1,
            Self::File => 2,
            Self::Multiple => 3,
        }
    }
    fn from_number(n: i64) -> Result<Self, Error> {
        match n {
            0 => Ok(Self::Text),
            1 => Ok(Self::Image),
            2 => Ok(Self::File),
            3 => Ok(Self::Multiple),
            _ => Err(Error::Corrupt),
        }
    }
}
#[derive(Clone, Debug)]
pub struct Input {
    pub representations: Vec<Representation>,
    pub source_application: String,
    pub observed_types: Vec<String>,
    pub copied_at_ms: u64,
}
#[derive(Clone, Debug)]
pub struct BundleInput {
    pub items: Vec<ClipboardItem>,
    pub source_application: String,
    pub observed_types: Vec<String>,
    pub copied_at_ms: u64,
}
impl From<Input> for BundleInput {
    fn from(v: Input) -> Self {
        Self {
            items: vec![ClipboardItem {
                representations: v.representations,
            }],
            source_application: v.source_application,
            observed_types: v.observed_types,
            copied_at_ms: v.copied_at_ms,
        }
    }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub id: u64,
    pub kind: Kind,
    pub preview: String,
    pub source_application: String,
    pub copied_at_ms: u64,
    pub pinned: bool,
    pub byte_count: u64,
    pub title: String,
    pub tags: Vec<String>,
    pub item_count: u32,
    pub ocr_indexed: bool,
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Annotation {
    pub title: String,
    pub tags: Vec<String>,
    pub ocr_text: String,
}
#[derive(Clone, Debug, Default)]
pub struct Filter {
    pub query: String,
    pub kind: Option<Kind>,
    pub source: Option<String>,
    pub tag: Option<String>,
    pub pinned_only: bool,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Stats {
    pub items: u32,
    pub bytes: u64,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ClearPreview {
    pub items: u32,
    pub bytes: u64,
    pub pinned_items: u32,
}

pub struct History {
    connection: Connection,
    limits: Limits,
    path: PathBuf,
}
impl History {
    pub fn open(path: impl AsRef<Path>, limits: Limits, now_ms: u64) -> Result<Self, Error> {
        let limits = limits.validate()?;
        timestamp(now_ms)?;
        let path = path.as_ref().to_path_buf();
        let mut connection = Connection::open(&path).map_err(database_error)?;
        connection.busy_timeout(std::time::Duration::from_secs(2))?;
        let version: i64 = connection
            .query_row("PRAGMA user_version", [], |r| r.get(0))
            .map_err(database_error)?;
        if version > SCHEMA_VERSION {
            return Err(Error::UnsupportedSchema);
        }
        if version < 0 {
            return Err(Error::Corrupt);
        }
        check_integrity(&connection)?;
        connection.execute_batch("PRAGMA foreign_keys=ON; PRAGMA secure_delete=ON; PRAGMA journal_mode=DELETE; PRAGMA trusted_schema=OFF;")?;
        if version == 0 {
            connection.execute_batch("PRAGMA auto_vacuum=INCREMENTAL;")?;
            let tx = connection.transaction()?;
            tx.execute_batch("CREATE TABLE entries (
                id INTEGER PRIMARY KEY AUTOINCREMENT, fingerprint TEXT NOT NULL UNIQUE,
                kind INTEGER NOT NULL, preview TEXT NOT NULL, search_text TEXT NOT NULL,
                source TEXT NOT NULL, copied_at INTEGER NOT NULL, pinned INTEGER NOT NULL DEFAULT 0,
                byte_count INTEGER NOT NULL, title TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '[]',
                metadata_search TEXT NOT NULL DEFAULT '', ocr_text TEXT NOT NULL DEFAULT '',
                ocr_search TEXT NOT NULL DEFAULT '', ocr_state INTEGER NOT NULL DEFAULT 0,
                item_count INTEGER NOT NULL DEFAULT 1, source_search TEXT NOT NULL DEFAULT ''
            ); CREATE TABLE representations (
                entry_id INTEGER NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
                item_index INTEGER NOT NULL, format TEXT NOT NULL, data BLOB NOT NULL,
                PRIMARY KEY(entry_id,item_index,format)
            ); CREATE INDEX entries_recency ON entries(pinned DESC,copied_at DESC,id DESC);
            CREATE INDEX pending_ocr ON entries(ocr_state,id);
            PRAGMA user_version=2;")?;
            tx.commit()?;
        } else if version == 1 {
            validate_schema(&connection, 1)?;
            let tx = connection.transaction()?;
            tx.execute_batch("ALTER TABLE entries ADD COLUMN title TEXT NOT NULL DEFAULT '';
                ALTER TABLE entries ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
                ALTER TABLE entries ADD COLUMN metadata_search TEXT NOT NULL DEFAULT '';
                ALTER TABLE entries ADD COLUMN ocr_text TEXT NOT NULL DEFAULT '';
                ALTER TABLE entries ADD COLUMN ocr_search TEXT NOT NULL DEFAULT '';
                ALTER TABLE entries ADD COLUMN ocr_state INTEGER NOT NULL DEFAULT 0;
                ALTER TABLE entries ADD COLUMN item_count INTEGER NOT NULL DEFAULT 1;
                ALTER TABLE entries ADD COLUMN source_search TEXT NOT NULL DEFAULT '';
                UPDATE entries SET source_search=lower(source);
                ALTER TABLE representations RENAME TO representations_v1;
                CREATE TABLE representations (entry_id INTEGER NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
                    item_index INTEGER NOT NULL,format TEXT NOT NULL,data BLOB NOT NULL,
                    PRIMARY KEY(entry_id,item_index,format));
                INSERT INTO representations SELECT entry_id,0,format,data FROM representations_v1;
                DROP TABLE representations_v1;
                CREATE INDEX pending_ocr ON entries(ocr_state,id);
                PRAGMA user_version=2;")?;
            tx.commit()?;
        }
        validate_schema(&connection, 2)?;
        let mut result = Self {
            connection,
            limits,
            path,
        };
        result.prune(now_ms)?;
        Ok(result)
    }
    pub fn configure(&mut self, limits: Limits, now_ms: u64) -> Result<(), Error> {
        let limits = limits.validate()?;
        let tx = self.connection.transaction()?;
        enforce_limits(&tx, limits, now_ms, None)?;
        tx.commit()?;
        self.limits = limits;
        self.reclaim_pages();
        Ok(())
    }
    pub fn record(&mut self, input: Input, policy: &CapturePolicy) -> Result<Option<u64>, Error> {
        self.record_bundle(input.into(), policy)
    }
    pub fn record_bundle(
        &mut self,
        input: BundleInput,
        policy: &CapturePolicy,
    ) -> Result<Option<u64>, Error> {
        if !should_capture(policy, &input.source_application, &input.observed_types) {
            return Ok(None);
        }
        let now = input.copied_at_ms;
        let Some(prepared) = prepare(input, self.limits)? else {
            return Ok(None);
        };
        let tx = self.connection.transaction()?;
        let id = insert_prepared(&tx, &prepared)?;
        enforce_limits(&tx, self.limits, now, Some(id))?;
        tx.commit()?;
        self.reclaim_pages();
        Ok(Some(id))
    }
    pub fn list(
        &mut self,
        query: &str,
        pinned_only: bool,
        offset: u32,
        limit: u32,
        now_ms: u64,
    ) -> Result<Vec<Entry>, Error> {
        self.list_filtered(
            &Filter {
                query: query.into(),
                pinned_only,
                ..Default::default()
            },
            offset,
            limit,
            now_ms,
        )
    }
    pub fn list_filtered(
        &mut self,
        filter: &Filter,
        offset: u32,
        limit: u32,
        now_ms: u64,
    ) -> Result<Vec<Entry>, Error> {
        self.prune(now_ms)?;
        let mut statement=self.connection.prepare("SELECT id,kind,preview,source,copied_at,pinned,byte_count,title,tags,item_count,ocr_state
            FROM entries WHERE (?1=0 OR pinned=1)
            AND (instr(search_text,?2)>0 OR instr(source_search,?2)>0 OR instr(metadata_search,?2)>0 OR instr(ocr_search,?2)>0)
            AND (?3 IS NULL OR kind=?3 OR (?3=0 AND EXISTS(SELECT 1 FROM representations WHERE entry_id=entries.id AND format='text/plain')) OR (?3=1 AND EXISTS(SELECT 1 FROM representations WHERE entry_id=entries.id AND format='image/png')) OR (?3=2 AND EXISTS(SELECT 1 FROM representations WHERE entry_id=entries.id AND format='text/uri-list'))) AND (?4 IS NULL OR source=?4)
            AND (?5 IS NULL OR EXISTS(SELECT 1 FROM json_each(entries.tags) WHERE lower(value)=?5))
            ORDER BY pinned DESC,copied_at DESC,id DESC LIMIT ?6 OFFSET ?7")?;
        let tag = filter.tag.as_ref().map(|s| s.trim().to_lowercase());
        let records = statement.query_map(
            params![
                filter.pinned_only,
                filter.query.to_lowercase(),
                filter.kind.map(Kind::number),
                filter.source,
                tag,
                limit.min(100),
                offset
            ],
            |r| {
                let n = r.get::<_, i64>(1)?;
                let kind = Kind::from_number(n).map_err(|_| rusqlite::Error::InvalidQuery)?;
                let tags: String = r.get(8)?;
                let tags =
                    serde_json::from_str(&tags).map_err(|_| rusqlite::Error::InvalidQuery)?;
                Ok(Entry {
                    id: r.get::<_, i64>(0)? as u64,
                    kind,
                    preview: r.get(2)?,
                    source_application: r.get(3)?,
                    copied_at_ms: r.get::<_, i64>(4)? as u64,
                    pinned: r.get(5)?,
                    byte_count: r.get::<_, i64>(6)? as u64,
                    title: r.get(7)?,
                    tags,
                    item_count: r.get(9)?,
                    ocr_indexed: r.get::<_, i64>(10)? == 1,
                })
            },
        )?;
        records.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }
    pub fn payload(&self, id: u64) -> Result<Vec<Representation>, Error> {
        let mut items = self.bundle(id)?;
        if items.len() != 1 {
            return Err(Error::InvalidInput);
        }
        Ok(items.remove(0).representations)
    }
    pub fn bundle(&self, id: u64) -> Result<Vec<ClipboardItem>, Error> {
        read_bundle(&self.connection, id, 2, self.limits.maximum_item_bytes)
    }
    pub fn annotation(&self, id: u64) -> Result<Annotation, Error> {
        self.connection
            .query_row(
                "SELECT title,tags,ocr_text FROM entries WHERE id=?1",
                [timestamp(id)?],
                |r| {
                    let tags: String = r.get(1)?;
                    Ok(Annotation {
                        title: r.get(0)?,
                        tags: serde_json::from_str(&tags)
                            .map_err(|_| rusqlite::Error::InvalidQuery)?,
                        ocr_text: r.get(2)?,
                    })
                },
            )
            .map_err(|e| match e {
                rusqlite::Error::QueryReturnedNoRows => Error::NotFound,
                other => other.into(),
            })
    }
    pub fn set_annotation(
        &mut self,
        id: u64,
        title: &str,
        tags: &[String],
        now_ms: u64,
    ) -> Result<(), Error> {
        let annotation = validated_annotation(title, tags, "")?;
        let old = self.annotation(id)?;
        let old_bytes = annotation_bytes(&old);
        let new = Annotation {
            ocr_text: old.ocr_text,
            ..annotation
        };
        let delta = annotation_bytes(&new) as i64 - old_bytes as i64;
        let tags = serde_json::to_string(&new.tags).map_err(|_| Error::InvalidInput)?;
        let tx = self.connection.transaction()?;
        tx.execute("UPDATE entries SET title=?1,tags=?2,metadata_search=?3,byte_count=byte_count+?4 WHERE id=?5",
            params![new.title,tags,metadata_search(&new),delta,timestamp(id)?])?;
        enforce_limits(&tx, self.limits, now_ms, Some(id))?;
        tx.commit()?;
        self.reclaim_pages();
        Ok(())
    }
    pub fn pending_ocr(&self, limit: u32) -> Result<Vec<u64>, Error> {
        let mut s=self.connection.prepare("SELECT id FROM entries WHERE ocr_state=0 AND EXISTS(
            SELECT 1 FROM representations WHERE entry_id=entries.id AND format='image/png') ORDER BY copied_at DESC,id DESC LIMIT ?1")?;
        s.query_map([limit.min(20)], |r| Ok(r.get::<_, i64>(0)? as u64))?
            .collect::<Result<Vec<_>, _>>()
            .map_err(Into::into)
    }
    pub fn store_ocr(&mut self, id: u64, text: &str, now_ms: u64) -> Result<(), Error> {
        if text.len() > MAX_OCR_BYTES {
            return Err(Error::TooLarge);
        }
        let old = self.annotation(id)?;
        let delta = (text.len() + text.to_lowercase().len()) as i64
            - (old.ocr_text.len() + old.ocr_text.to_lowercase().len()) as i64;
        let tx = self.connection.transaction()?;
        if tx.execute("UPDATE entries SET ocr_text=?1,ocr_search=?2,ocr_state=1,byte_count=byte_count+?3
            WHERE id=?4 AND EXISTS(SELECT 1 FROM representations WHERE entry_id=entries.id AND format='image/png')",
            params![text,text.to_lowercase(),delta,timestamp(id)?])? == 0 { return Err(Error::InvalidInput); }
        enforce_limits(&tx, self.limits, now_ms, Some(id))?;
        tx.commit()?;
        self.reclaim_pages();
        Ok(())
    }
    pub fn mark_ocr_failed(&self, id: u64) -> Result<(), Error> {
        if self.connection.execute(
            "UPDATE entries SET ocr_state=2 WHERE id=?1",
            [timestamp(id)?],
        )? == 0
        {
            return Err(Error::NotFound);
        }
        Ok(())
    }
    pub fn retry_ocr(&self) -> Result<(), Error> {
        self.connection
            .execute("UPDATE entries SET ocr_state=0 WHERE ocr_state=2", [])?;
        Ok(())
    }
    pub fn sources(&self) -> Result<Vec<String>, Error> {
        string_column(
            &self.connection,
            "SELECT DISTINCT source FROM entries WHERE source!='' ORDER BY source",
        )
    }
    pub fn tags(&self) -> Result<Vec<String>, Error> {
        string_column(
            &self.connection,
            "SELECT DISTINCT value FROM entries,json_each(entries.tags) ORDER BY value",
        )
    }
    pub fn set_pinned(&mut self, id: u64, pinned: bool, now_ms: u64) -> Result<(), Error> {
        let tx = self.connection.transaction()?;
        if tx.execute(
            "UPDATE entries SET pinned=?1 WHERE id=?2",
            params![pinned, timestamp(id)?],
        )? == 0
        {
            return Err(Error::NotFound);
        }
        enforce_limits(&tx, self.limits, now_ms, None)?;
        tx.commit()?;
        self.reclaim_pages();
        Ok(())
    }
    pub fn delete(&mut self, id: u64) -> Result<(), Error> {
        if self
            .connection
            .execute("DELETE FROM entries WHERE id=?1", [timestamp(id)?])?
            == 0
        {
            return Err(Error::NotFound);
        }
        self.reclaim_pages();
        Ok(())
    }
    pub fn clear_preview(&self, include_pinned: bool) -> Result<ClearPreview, Error> {
        self.connection.query_row("SELECT count(*),coalesce(sum(byte_count),0),coalesce(sum(pinned),0) FROM entries WHERE ?1=1 OR pinned=0",[include_pinned],|r| {
            Ok(ClearPreview {items:r.get(0)?,bytes:r.get::<_,i64>(1)? as u64,pinned_items:r.get(2)?})
        }).map_err(Into::into)
    }
    pub fn clear(&mut self, include_pinned: bool) -> Result<(), Error> {
        self.connection.execute(
            "DELETE FROM entries WHERE ?1=1 OR pinned=0",
            [include_pinned],
        )?;
        self.reclaim_pages();
        Ok(())
    }
    pub fn stats(&self) -> Result<Stats, Error> {
        stats(&self.connection)
    }
    fn prune(&mut self, now_ms: u64) -> Result<(), Error> {
        let tx = self.connection.transaction()?;
        enforce_limits(&tx, self.limits, now_ms, None)?;
        tx.commit()?;
        self.reclaim_pages();
        Ok(())
    }
    // Maintenance after a successful commit must not report the write as rejected.
    fn reclaim_pages(&self) {
        let _ = self
            .connection
            .execute_batch("PRAGMA incremental_vacuum(128);");
    }
}

struct Prepared {
    input: BundleInput,
    fingerprint: String,
    kind: Kind,
    preview: String,
    search: String,
    byte_count: u64,
}
fn prepare(input: BundleInput, limits: Limits) -> Result<Option<Prepared>, Error> {
    timestamp(input.copied_at_ms)?;
    if input.source_application.len() > 512
        || input.items.is_empty()
        || input.items.len() > MAX_BUNDLE_ITEMS
    {
        return Err(Error::InvalidInput);
    }
    let mut payload_bytes = 0u64;
    let mut identities = Vec::new();
    let mut previews = Vec::new();
    let mut searchable = Vec::new();
    for item in &input.items {
        if item.representations.is_empty() {
            return Err(Error::InvalidInput);
        }
        let mut formats = std::collections::HashSet::new();
        for r in &item.representations {
            if !ALLOWED_FORMATS.contains(&r.format.as_str())
                || r.bytes.is_empty()
                || !formats.insert(&r.format)
            {
                return Err(Error::InvalidInput);
            }
            if r.format == "image/png" && !r.bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
                return Err(Error::InvalidInput);
            }
            payload_bytes = payload_bytes
                .checked_add(r.bytes.len() as u64)
                .ok_or(Error::TooLarge)?;
        }
        if payload_bytes > limits.maximum_item_bytes {
            return Err(Error::TooLarge);
        }
        let plain = item
            .representations
            .iter()
            .find(|r| r.format == "text/plain");
        let image = item
            .representations
            .iter()
            .find(|r| r.format == "image/png");
        let file = item
            .representations
            .iter()
            .find(|r| r.format == FILE_FORMAT);
        let (kind, primary, preview, search) = if let Some(file) = file {
            if item.representations.len() != 1 {
                return Err(Error::InvalidInput);
            }
            let value = std::str::from_utf8(&file.bytes).map_err(|_| Error::InvalidInput)?;
            let parsed = url::Url::parse(value).map_err(|_| Error::InvalidInput)?;
            if parsed.scheme() != "file"
                || parsed.query().is_some()
                || parsed.fragment().is_some()
                || parsed.path().is_empty()
            {
                return Err(Error::InvalidInput);
            }
            let path = percent_encoding::percent_decode_str(parsed.path())
                .decode_utf8()
                .map_err(|_| Error::InvalidInput)?
                .into_owned();
            let preview = path
                .rsplit('/')
                .find(|s| !s.is_empty())
                .unwrap_or(&path)
                .chars()
                .take(160)
                .collect();
            (Kind::File, &file.bytes, preview, path.to_lowercase())
        } else if let Some(plain) = plain {
            let value = std::str::from_utf8(&plain.bytes).map_err(|_| Error::InvalidInput)?;
            if value.trim().is_empty() && input.items.len() == 1 {
                return Ok(None);
            }
            (
                Kind::Text,
                &plain.bytes,
                value.chars().take(160).collect(),
                value.to_lowercase(),
            )
        } else if let Some(image) = image {
            if item.representations.len() != 1 || !image.bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
                return Err(Error::InvalidInput);
            }
            (Kind::Image, &image.bytes, String::new(), String::new())
        } else {
            return Err(Error::InvalidInput);
        };
        identities.push((kind, primary));
        previews.push(preview);
        searchable.push(search);
    }
    let kind = if input.items.len() == 1 {
        identities[0].0
    } else {
        Kind::Multiple
    };
    let preview = if input.items.len() == 1 {
        previews.remove(0)
    } else {
        previews
            .iter()
            .map(|s| if s.is_empty() { "[image]" } else { s.as_str() })
            .collect::<Vec<_>>()
            .join(" · ")
            .chars()
            .take(160)
            .collect()
    };
    let search = searchable.join("\n");
    let byte_count = payload_bytes
        + preview.len() as u64
        + search.len() as u64
        + input.source_application.len() as u64;
    if byte_count > limits.maximum_bytes {
        return Err(Error::TooLarge);
    }
    let mut hash = Sha256::new();
    hash.update([kind.number() as u8]);
    if identities.len() == 1 {
        hash.update(identities[0].1);
    } else {
        for (kind, bytes) in identities {
            hash.update([kind.number() as u8]);
            hash.update((bytes.len() as u64).to_be_bytes());
            hash.update(bytes);
        }
    }
    Ok(Some(Prepared {
        input,
        fingerprint: format!("{:x}", hash.finalize()),
        kind,
        preview,
        search,
        byte_count,
    }))
}
fn insert_prepared(tx: &Transaction<'_>, p: &Prepared) -> Result<u64, Error> {
    tx.execute("INSERT INTO entries (fingerprint,kind,preview,search_text,source,source_search,copied_at,byte_count,item_count)
        VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9) ON CONFLICT(fingerprint) DO UPDATE SET
        preview=excluded.preview,search_text=excluded.search_text,source=excluded.source,source_search=excluded.source_search,
        copied_at=excluded.copied_at,byte_count=excluded.byte_count+length(CAST(title AS BLOB))+length(CAST(metadata_search AS BLOB))+
            length(CAST(ocr_text AS BLOB))+length(CAST(ocr_search AS BLOB)),item_count=excluded.item_count",
        params![p.fingerprint,p.kind.number(),p.preview,p.search,p.input.source_application,p.input.source_application.to_lowercase(),timestamp(p.input.copied_at_ms)?,p.byte_count as i64,p.input.items.len() as i64])?;
    let id: i64 = tx.query_row(
        "SELECT id FROM entries WHERE fingerprint=?1",
        [&p.fingerprint],
        |r| r.get(0),
    )?;
    tx.execute("DELETE FROM representations WHERE entry_id=?1", [id])?;
    for (i, item) in p.input.items.iter().enumerate() {
        for r in &item.representations {
            tx.execute(
                "INSERT INTO representations VALUES (?1,?2,?3,?4)",
                params![id, i as i64, r.format, r.bytes],
            )?;
        }
    }
    Ok(id as u64)
}
fn read_bundle(
    connection: &Connection,
    id: u64,
    version: i64,
    maximum_bytes: u64,
) -> Result<Vec<ClipboardItem>, Error> {
    let (bytes, count): (i64, u32) = connection.query_row(
        "SELECT coalesce(sum(length(data)),0),count(*) FROM representations WHERE entry_id=?1",
        [timestamp(id)?],
        |r| Ok((r.get(0)?, r.get(1)?)),
    )?;
    if bytes < 0 || bytes as u64 > maximum_bytes || count > 500 {
        return Err(Error::TooLarge);
    }
    let sql = if version == 1 {
        "SELECT 0,format,data FROM representations WHERE entry_id=?1 ORDER BY format"
    } else {
        "SELECT item_index,format,data FROM representations WHERE entry_id=?1 ORDER BY item_index,format"
    };
    let mut s = connection.prepare(sql)?;
    let mut rows = s.query([timestamp(id)?])?;
    let mut items: Vec<ClipboardItem> = Vec::new();
    while let Some(r) = rows.next()? {
        let index = r.get::<_, i64>(0)? as usize;
        if index >= MAX_BUNDLE_ITEMS || index > items.len() {
            return Err(Error::Corrupt);
        }
        if index == items.len() {
            items.push(ClipboardItem {
                representations: vec![],
            });
        }
        items[index].representations.push(Representation {
            format: r.get(1)?,
            bytes: r.get(2)?,
        });
    }
    if items.is_empty() {
        return Err(Error::NotFound);
    }
    Ok(items)
}
fn validated_annotation(title: &str, tags: &[String], ocr: &str) -> Result<Annotation, Error> {
    let title = title.trim();
    if title.chars().count() > 120
        || title.len() > 512
        || tags.len() > 20
        || ocr.len() > MAX_OCR_BYTES
    {
        return Err(Error::InvalidInput);
    }
    let mut unique = std::collections::HashSet::new();
    let mut normalized = Vec::new();
    for tag in tags {
        let tag = tag.trim();
        if tag.is_empty() {
            continue;
        }
        if tag.chars().count() > 64 || tag.len() > 256 {
            return Err(Error::InvalidInput);
        }
        // Store canonical tag spelling so Unicode exact filters do not depend on SQLite lower().
        let tag = tag.to_lowercase();
        if unique.insert(tag.clone()) {
            normalized.push(tag);
        }
    }
    Ok(Annotation {
        title: title.into(),
        tags: normalized,
        ocr_text: ocr.into(),
    })
}
fn metadata_search(a: &Annotation) -> String {
    if a.title.is_empty() && a.tags.is_empty() {
        String::new()
    } else {
        format!("{}\n{}", a.title, a.tags.join("\n")).to_lowercase()
    }
}
fn annotation_bytes(a: &Annotation) -> u64 {
    // The empty metadata column is zero bytes in a fresh row.
    let metadata = if a.title.is_empty() && a.tags.is_empty() {
        String::new()
    } else {
        metadata_search(a)
    };
    (a.title.len() + metadata.len() + a.ocr_text.len() + a.ocr_text.to_lowercase().len()) as u64
}
fn timestamp(value: u64) -> Result<i64, Error> {
    i64::try_from(value).map_err(|_| Error::InvalidInput)
}
fn stats(connection: &Connection) -> Result<Stats, Error> {
    connection
        .query_row(
            "SELECT count(*),coalesce(sum(byte_count),0) FROM entries",
            [],
            |r| {
                Ok(Stats {
                    items: r.get(0)?,
                    bytes: r.get::<_, i64>(1)? as u64,
                })
            },
        )
        .map_err(Into::into)
}
fn enforce_limits(
    tx: &Transaction<'_>,
    limits: Limits,
    now_ms: u64,
    protected: Option<u64>,
) -> Result<(), Error> {
    timestamp(now_ms)?;
    let protected = protected.map(timestamp).transpose()?;
    if limits.retention_days > 0 {
        let cutoff = now_ms.saturating_sub(u64::from(limits.retention_days) * DAY_MS);
        tx.execute(
            "DELETE FROM entries WHERE pinned=0 AND copied_at<?1 AND (?2 IS NULL OR id!=?2)",
            params![timestamp(cutoff)?, protected],
        )?;
    }
    loop {
        let current = stats(tx)?;
        if current.items <= limits.maximum_items && current.bytes <= limits.maximum_bytes {
            return Ok(());
        }
        let victim=tx.query_row("SELECT id FROM entries WHERE pinned=0 AND (?1 IS NULL OR id!=?1) ORDER BY copied_at,id LIMIT 1",[protected],|r|r.get::<_,i64>(0));
        match victim {
            Ok(id) => {
                tx.execute("DELETE FROM entries WHERE id=?1", [id])?;
            }
            Err(rusqlite::Error::QueryReturnedNoRows) => return Err(Error::Capacity),
            Err(e) => return Err(e.into()),
        }
    }
}
fn string_column(connection: &Connection, sql: &str) -> Result<Vec<String>, Error> {
    let mut s = connection.prepare(sql)?;
    s.query_map([], |r| r.get(0))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(Into::into)
}
fn database_error(error: rusqlite::Error) -> Error {
    if let rusqlite::Error::SqliteFailure(ref code, _) = error {
        if matches!(
            code.code,
            rusqlite::ErrorCode::DatabaseCorrupt | rusqlite::ErrorCode::NotADatabase
        ) {
            return Error::Corrupt;
        }
    }
    Error::Storage(error)
}
fn check_integrity(connection: &Connection) -> Result<(), Error> {
    let result: String = connection
        .query_row("PRAGMA quick_check(1)", [], |r| r.get(0))
        .map_err(database_error)?;
    if result != "ok" {
        return Err(Error::Corrupt);
    }
    Ok(())
}
fn validate_schema(connection: &Connection, version: i64) -> Result<(), Error> {
    for table in ["entries", "representations"] {
        let kind: Option<String> = connection
            .query_row(
                "SELECT type FROM sqlite_schema WHERE name=?1",
                [table],
                |r| r.get(0),
            )
            .ok();
        if kind.as_deref() != Some("table") {
            return Err(Error::Corrupt);
        }
    }
    let sql = if version == 1 {
        "SELECT id,fingerprint,kind,preview,search_text,source,copied_at,pinned,byte_count FROM entries LIMIT 0"
    } else {
        "SELECT id,fingerprint,kind,preview,search_text,source,copied_at,pinned,byte_count,title,tags,metadata_search,ocr_text,ocr_search,ocr_state,item_count,source_search FROM entries LIMIT 0"
    };
    connection.prepare(sql).map_err(|_| Error::Corrupt)?;
    connection
        .prepare(if version == 1 {
            "SELECT entry_id,format,data FROM representations LIMIT 0"
        } else {
            "SELECT entry_id,item_index,format,data FROM representations LIMIT 0"
        })
        .map_err(|_| Error::Corrupt)?;
    Ok(())
}
pub fn image_dimensions_allowed(width: u64, height: u64) -> bool {
    width > 0
        && height > 0
        && width
            .checked_mul(height)
            .is_some_and(|pixels| pixels <= 16_000_000)
}

/// Explicitly combines text items for plain-text paste; mixed content is never flattened.
pub fn plain_text(items: &[ClipboardItem]) -> Option<String> {
    if items.is_empty() {
        return None;
    }
    items
        .iter()
        .map(|item| {
            item.representations
                .iter()
                .find(|r| r.format == "text/plain")
                .and_then(|r| std::str::from_utf8(&r.bytes).ok())
                .map(str::to_owned)
        })
        .collect::<Option<Vec<_>>>()
        .map(|parts| parts.join("\n"))
}
