//! Local clipboard history. No clipboard APIs, GUI dependencies, or FFI types.
use rusqlite::{Connection, Transaction, params};
use sha2::{Digest, Sha256};
use std::path::Path;

const SCHEMA_VERSION: i64 = 1;
const DAY_MS: u64 = 86_400_000;
const ALLOWED_FORMATS: &[&str] = &["text/plain", "text/html", "text/rtf", "image/png"];
const PRIVATE_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
];

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("invalid history configuration or content")]
    InvalidInput,
    #[error("unsupported database schema")]
    UnsupportedSchema,
    #[error("clipboard content exceeds the per-item limit")]
    TooLarge,
    #[error("pinned records fill the history capacity")]
    Capacity,
    #[error("history record does not exist")]
    NotFound,
    #[error("history storage failed")]
    Storage(#[from] rusqlite::Error),
}

#[derive(Clone, Copy, Debug)]
pub struct Limits {
    pub maximum_items: u32,
    pub maximum_bytes: u64,
    pub maximum_item_bytes: u64,
    /// Zero means no expiration. Pinned records never expire automatically.
    pub retention_days: u32,
}
impl Default for Limits {
    fn default() -> Self {
        Self {
            maximum_items: 500,
            maximum_bytes: 256 * 1024 * 1024,
            maximum_item_bytes: 16 * 1024 * 1024,
            retention_days: 30,
        }
    }
}
impl Limits {
    pub fn validate(self) -> Result<Self, Error> {
        if self.maximum_items == 0
            || self.maximum_items > 10_000
            || self.maximum_item_bytes == 0
            || self.maximum_item_bytes > self.maximum_bytes
            || self.maximum_bytes > 2 * 1024 * 1024 * 1024
            || self.retention_days > 3650
        {
            return Err(Error::InvalidInput);
        }
        Ok(self)
    }
}

#[derive(Clone, Debug, Default)]
pub struct CapturePolicy {
    pub enabled: bool,
    pub ignored_applications: Vec<String>,
    pub ignored_types: Vec<String>,
}
/// Called before reading expensive clipboard representations, and again on insert.
pub fn should_capture(policy: &CapturePolicy, source: &str, types: &[String]) -> bool {
    policy.enabled
        && !policy.ignored_applications.iter().any(|app| app == source)
        && !types
            .iter()
            .any(|ty| PRIVATE_TYPES.contains(&ty.as_str()) || policy.ignored_types.contains(ty))
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Representation {
    pub format: String,
    pub bytes: Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Text,
    Image,
}
#[derive(Clone, Debug)]
pub struct Input {
    pub representations: Vec<Representation>,
    pub source_application: String,
    pub observed_types: Vec<String>,
    pub copied_at_ms: u64,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub id: u64,
    pub kind: Kind,
    pub preview: String,
    pub source_application: String,
    pub copied_at_ms: u64,
    pub pinned: bool,
    pub byte_count: u64,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Stats {
    pub items: u32,
    pub bytes: u64,
}

pub struct History {
    connection: Connection,
    limits: Limits,
}
impl History {
    /// The platform supplies a private, application-specific database path.
    pub fn open(path: impl AsRef<Path>, limits: Limits, now_ms: u64) -> Result<Self, Error> {
        let limits = limits.validate()?;
        timestamp(now_ms)?;
        let mut connection = Connection::open(path)?;
        connection.busy_timeout(std::time::Duration::from_secs(2))?;
        let version: i64 = connection.query_row("PRAGMA user_version", [], |r| r.get(0))?;
        if version > SCHEMA_VERSION {
            return Err(Error::UnsupportedSchema);
        }
        // DELETE journaling avoids leaving clipboard payloads in a long-lived WAL.
        connection.execute_batch(
            "PRAGMA foreign_keys=ON; PRAGMA secure_delete=ON; PRAGMA journal_mode=DELETE;",
        )?;
        if version == 0 {
            connection.execute_batch("PRAGMA auto_vacuum=INCREMENTAL;")?;
            let tx = connection.transaction()?;
            tx.execute_batch(
                "CREATE TABLE entries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                fingerprint TEXT NOT NULL UNIQUE,
                kind INTEGER NOT NULL,
                preview TEXT NOT NULL,
                search_text TEXT NOT NULL,
                source TEXT NOT NULL,
                copied_at INTEGER NOT NULL,
                pinned INTEGER NOT NULL DEFAULT 0,
                byte_count INTEGER NOT NULL
            );
            CREATE TABLE representations (
                entry_id INTEGER NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
                format TEXT NOT NULL,
                data BLOB NOT NULL,
                PRIMARY KEY (entry_id, format)
            );
            CREATE INDEX entries_recency ON entries(pinned DESC, copied_at DESC, id DESC);
            PRAGMA user_version=1;",
            )?;
            tx.commit()?;
        }
        let mut result = Self { connection, limits };
        result.prune(now_ms)?;
        Ok(result)
    }

    pub fn configure(&mut self, limits: Limits, now_ms: u64) -> Result<(), Error> {
        let limits = limits.validate()?;
        let tx = self.connection.transaction()?;
        enforce_limits(&tx, limits, now_ms, None)?;
        tx.commit()?;
        self.limits = limits;
        self.reclaim_pages()?;
        Ok(())
    }

    /// A filtered capture returns None and never touches persistence.
    pub fn record(&mut self, input: Input, policy: &CapturePolicy) -> Result<Option<u64>, Error> {
        if !should_capture(policy, &input.source_application, &input.observed_types) {
            return Ok(None);
        }
        let copied_at = timestamp(input.copied_at_ms)?;
        if input.source_application.len() > 512 || input.representations.is_empty() {
            return Err(Error::InvalidInput);
        }
        let mut formats = std::collections::HashSet::new();
        let mut payload_bytes = 0u64;
        for representation in &input.representations {
            if !ALLOWED_FORMATS.contains(&representation.format.as_str())
                || representation.bytes.is_empty()
                || !formats.insert(&representation.format)
            {
                return Err(Error::InvalidInput);
            }
            payload_bytes = payload_bytes
                .checked_add(representation.bytes.len() as u64)
                .ok_or(Error::TooLarge)?;
        }
        if payload_bytes > self.limits.maximum_item_bytes {
            return Err(Error::TooLarge);
        }
        let plain = input
            .representations
            .iter()
            .find(|r| r.format == "text/plain");
        let image = input
            .representations
            .iter()
            .find(|r| r.format == "image/png");
        let (kind, primary, preview, search_text) = if let Some(plain) = plain {
            let text = std::str::from_utf8(&plain.bytes).map_err(|_| Error::InvalidInput)?;
            if text.trim().is_empty() {
                return Ok(None);
            }
            (
                Kind::Text,
                &plain.bytes,
                text.chars().take(160).collect::<String>(),
                text.to_lowercase(),
            )
        } else if let Some(image) = image {
            if !image.bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
                return Err(Error::InvalidInput);
            }
            (Kind::Image, &image.bytes, String::new(), String::new())
        } else {
            return Err(Error::InvalidInput);
        };
        let byte_count = payload_bytes
            + preview.len() as u64
            + search_text.len() as u64
            + input.source_application.len() as u64;
        if byte_count > self.limits.maximum_bytes {
            return Err(Error::TooLarge);
        }
        let mut hash = Sha256::new();
        hash.update([match kind {
            Kind::Text => 0,
            Kind::Image => 1,
        }]);
        hash.update(primary);
        let fingerprint = format!("{:x}", hash.finalize());
        let tx = self.connection.transaction()?;
        tx.execute(
            "INSERT INTO entries (fingerprint,kind,preview,search_text,source,copied_at,byte_count)
            VALUES (?1,?2,?3,?4,?5,?6,?7)
            ON CONFLICT(fingerprint) DO UPDATE SET preview=excluded.preview,
            search_text=excluded.search_text, source=excluded.source,
            copied_at=excluded.copied_at, byte_count=excluded.byte_count",
            params![
                fingerprint,
                match kind {
                    Kind::Text => 0,
                    Kind::Image => 1,
                },
                preview,
                search_text,
                input.source_application,
                copied_at,
                byte_count as i64
            ],
        )?;
        let id: i64 = tx.query_row(
            "SELECT id FROM entries WHERE fingerprint=?1",
            [&fingerprint],
            |r| r.get(0),
        )?;
        tx.execute("DELETE FROM representations WHERE entry_id=?1", [id])?;
        for representation in input.representations {
            tx.execute(
                "INSERT INTO representations VALUES (?1,?2,?3)",
                params![id, representation.format, representation.bytes],
            )?;
        }
        // The incoming item must either fit or roll back; never report an evicted item as saved.
        enforce_limits(&tx, self.limits, input.copied_at_ms, Some(id as u64))?;
        tx.commit()?;
        self.reclaim_pages()?;
        Ok(Some(id as u64))
    }

    /// SQL searches a normalized column; list results never load image or rich-text blobs.
    pub fn list(
        &mut self,
        query: &str,
        pinned_only: bool,
        offset: u32,
        limit: u32,
        now_ms: u64,
    ) -> Result<Vec<Entry>, Error> {
        self.prune(now_ms)?;
        let mut statement = self.connection.prepare(
            "SELECT id,kind,preview,source,copied_at,pinned,byte_count FROM entries
            WHERE (?1=0 OR pinned=1) AND (instr(search_text,?2)>0 OR instr(lower(source),?2)>0)
            ORDER BY pinned DESC,copied_at DESC,id DESC LIMIT ?3 OFFSET ?4",
        )?;
        let records = statement.query_map(
            params![pinned_only, query.to_lowercase(), limit.min(100), offset],
            |r| {
                Ok(Entry {
                    id: r.get::<_, i64>(0)? as u64,
                    kind: if r.get::<_, i64>(1)? == 0 {
                        Kind::Text
                    } else {
                        Kind::Image
                    },
                    preview: r.get(2)?,
                    source_application: r.get(3)?,
                    copied_at_ms: r.get::<_, i64>(4)? as u64,
                    pinned: r.get(5)?,
                    byte_count: r.get::<_, i64>(6)? as u64,
                })
            },
        )?;
        records.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    pub fn payload(&self, id: u64) -> Result<Vec<Representation>, Error> {
        let mut statement = self
            .connection
            .prepare("SELECT format,data FROM representations WHERE entry_id=?1 ORDER BY format")?;
        let result = statement
            .query_map([timestamp(id)?], |r| {
                Ok(Representation {
                    format: r.get(0)?,
                    bytes: r.get(1)?,
                })
            })?
            .collect::<Result<Vec<_>, _>>()?;
        if result.is_empty() {
            return Err(Error::NotFound);
        }
        Ok(result)
    }
    pub fn set_pinned(&mut self, id: u64, pinned: bool, now_ms: u64) -> Result<(), Error> {
        let tx = self.connection.transaction()?;
        if tx.execute(
            "UPDATE entries SET pinned=?1 WHERE id=?2",
            params![pinned, timestamp(id)?],
        )? == 0
        {
            return Err(Error::NotFound);
        }
        enforce_limits(&tx, self.limits, now_ms, None)?;
        tx.commit()?;
        self.reclaim_pages()
    }
    pub fn delete(&mut self, id: u64) -> Result<(), Error> {
        if self
            .connection
            .execute("DELETE FROM entries WHERE id=?1", [timestamp(id)?])?
            == 0
        {
            return Err(Error::NotFound);
        }
        self.reclaim_pages()
    }
    pub fn clear(&mut self, include_pinned: bool) -> Result<(), Error> {
        self.connection.execute(
            "DELETE FROM entries WHERE ?1=1 OR pinned=0",
            [include_pinned],
        )?;
        self.reclaim_pages()
    }
    pub fn stats(&self) -> Result<Stats, Error> {
        stats(&self.connection)
    }
    fn prune(&mut self, now_ms: u64) -> Result<(), Error> {
        let tx = self.connection.transaction()?;
        enforce_limits(&tx, self.limits, now_ms, None)?;
        tx.commit()?;
        self.reclaim_pages()
    }
    fn reclaim_pages(&self) -> Result<(), Error> {
        self.connection
            .execute_batch("PRAGMA incremental_vacuum;")?;
        Ok(())
    }
}
fn timestamp(value: u64) -> Result<i64, Error> {
    i64::try_from(value).map_err(|_| Error::InvalidInput)
}
fn stats(connection: &Connection) -> Result<Stats, Error> {
    Ok(connection.query_row(
        "SELECT count(*),coalesce(sum(byte_count),0) FROM entries",
        [],
        |r| {
            Ok(Stats {
                items: r.get(0)?,
                bytes: r.get::<_, i64>(1)? as u64,
            })
        },
    )?)
}
fn enforce_limits(
    tx: &Transaction<'_>,
    limits: Limits,
    now_ms: u64,
    protected: Option<u64>,
) -> Result<(), Error> {
    timestamp(now_ms)?;
    let protected = protected.map(timestamp).transpose()?;
    if limits.retention_days > 0 {
        let cutoff = now_ms.saturating_sub(u64::from(limits.retention_days) * DAY_MS);
        tx.execute(
            "DELETE FROM entries WHERE pinned=0 AND copied_at<?1 AND (?2 IS NULL OR id!=?2)",
            params![timestamp(cutoff)?, protected],
        )?;
    }
    loop {
        let current = stats(tx)?;
        if current.items <= limits.maximum_items && current.bytes <= limits.maximum_bytes {
            return Ok(());
        }
        let victim = tx.query_row(
            "SELECT id FROM entries WHERE pinned=0 AND (?1 IS NULL OR id!=?1)
            ORDER BY copied_at,id LIMIT 1",
            [protected],
            |r| r.get::<_, i64>(0),
        );
        match victim {
            Ok(id) => {
                tx.execute("DELETE FROM entries WHERE id=?1", [id])?;
            }
            Err(rusqlite::Error::QueryReturnedNoRows) => return Err(Error::Capacity),
            Err(error) => return Err(error.into()),
        }
    }
}

/// Bounds native image decoding on every frontend without importing an image library.
pub fn image_dimensions_allowed(width: u64, height: u64) -> bool {
    width > 0
        && height > 0
        && width
            .checked_mul(height)
            .is_some_and(|pixels| pixels <= 16_000_000)
}
